//database to hold level data
Sol.levels= {
	//title level
	0: '{"number":"0","author":"Chris","size":[15,7],"level":[[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],[{},{},{},{"id":93,"start":"right"},{},{"id":95,"note":"_do"},{},{"id":97,"note":"mi"},{},{"id":99,"note":"sol"},{},{"id":101,"note":"do"},{},{},{}]],"solution":[["_do"],[],["mi"],[],["sol"],[],["do"]]}',
	/////////////////////////////////////////////////////
	//_do and do introduced, vertical gates introduced
	/////////////////////////////////////////////////////
	1: '{"number":"1","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{},{},{},{},{}],[{},{"id":9,"obstacle":"vertGate"},{"id":10,"start":"right","note":"do"},{"id":11,"obstacle":"vertGate"},{"id":12,"note":"_do"},{"id":13,"obstacle":"vertGate"},{"id":14,"note":"do"},{"id":15,"obstacle":"vertGate"}],[{},{},{},{},{},{},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],["do"],[],["do"],[],["_do"],[],["do"],[],[]],"viewportOffset":[100,-100]}',
	//rotating obstacles intoduced, syncopation
	2: '{"number":"2","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{},{},{},{},{}],[{},{},{"id":10,"obstacle":"forward"},{"id":11,"note":"do"},{},{"id":13,"note":"_do","obstacle":"back"},{},{}],[{},{},{"id":18,"obstacle":"forward"},{"id":19,"note":"_do"},{"id":20,"start":"right"},{"id":21,"obstacle":"hor"},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],[],["_do"],[],[],["do"],[],["_do"]],"viewportOffset":[0,0]}',
	////////////////////
	//sol introduced
	////////////////////
	3: '{"number":"3","author":"Chris","size":[8,4],"level":[[{},{},{},{},{},{},{},{}],[{},{},{},{"id":11,"note":"do","obstacle":"back"},{},{"id":13,"note":"_do","obstacle":"forward"},{},{}],[{},{},{},{"id":19,"start":"up"},{},{},{},{}],[{},{},{},{"id":27,"obstacle":"hor"},{"id":28,"note":"sol"},{"id":29,"obstacle":"forward"},{},{}]],"solution":[["do"],[],[],["sol"],[],[],["_do"],[],["do"]],"viewportOffset":[100,100]}',
	//diagonal gates introduced
	4: '{"number":"4","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{"id":2,"obstacle":"hor"},{"id":3,"note":"do"},{"id":4,"obstacle":"vert"},{},{},{}],[{},{"id":9,"start":"right"},{"id":10,"note":"_do"},{"id":11,"obstacle":"backGate"},{"id":12,"obstacle":"back"},{},{},{}],[{},{},{"id":18,"obstacle":"back"},{"id":19,"obstacle":"back"},{"id":20,"obstacle":"forward","note":"sol"},{},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],[],["sol"],[],[],["do"],[],["_do"]],"viewportOffset":[-100,-100]}',
	5: '{"number":"5","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{},{},{},{},{}],[{},{},{"id":10,"obstacle":"forward"},{"id":11,"obstacle":"vertGate"},{"id":12,"note":"sol"},{"id":13,"obstacle":"hor"},{},{}],[{},{},{"id":18,"obstacle":"vert","note":"do"},{"id":19,"start":"right"},{"id":20,"note":"_do","obstacle":"vertGate"},{"id":21,"obstacle":"forward"},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],["do"],[],[],["sol"],[],["sol"],[],[],["do"],[],["_do"]],"viewportOffset":[0,0]}',
	6: '{"number":"6","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{"id":3,"obstacle":"forward","note":"sol"},{"id":4,"obstacle":"back"},{},{},{}],[{},{},{},{},{},{},{},{}],[{},{},{"id":18,"start":"right"},{"id":19,"obstacle":"backGate"},{"id":20,"obstacle":"back","note":"_do"},{},{},{}],[{},{},{},{"id":27,"obstacle":"back","note":"do"},{"id":28,"obstacle":"forward"},{},{},{}]],"solution":[["do"],[],[],["sol"],[],[],["_do"],[],["do"]],"viewportOffset":[0,0]}',
	//wormholes introduced
	7: '{"number":"7","author":"Chris","size":[8,4],"wormholeStart":[3,1],"wormholeEnd":[4,2],"level":[[{},{},{},{},{},{},{},{}],[{},{},{"id":10,"obstacle":"vert","note":"do"},{"id":11,"wormhole":"wormholeStart"},{"id":12,"start":"right"},{"id":13,"note":"_do","obstacle":"back"},{},{}],[{},{},{"id":18,"obstacle":"back"},{"id":19,"note":"sol"},{"id":20,"wormhole":"wormholeEnd"},{"id":21,"obstacle":"forward"},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],[],["sol"],[],["do"],[],[],["_do"]],"viewportOffset":[0,0]}',
	8: '{"number":"8","author":"Chris","size":[8,4],"wormholeStart":[5,2],"wormholeEnd":[3,0],"level":[[{},{},{},{"id":3,"wormhole":"wormholeEnd"},{"id":4,"note":"do","obstacle":"back"},{"id":5,"obstacle":"back"},{},{}],[{},{},{"id":10,"start":"right"},{"id":11,"note":"sol"},{"id":12,"obstacle":"vert"},{"id":13,"obstacle":"forward","note":"do"},{},{}],[{},{},{},{"id":19,"obstacle":"hor"},{"id":20,"note":"_do","obstacle":"back"},{"id":21,"wormhole":"wormholeStart"},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["sol"],[],["do"],[],["sol"],[],["_do"],[],["do"]],"viewportOffset":[100,-100]}',
	9: '{"number":"9","author":"Chris","size":[8,4],"wormholeStart":[6,2],"wormholeEnd":[2,1],"level":[[{},{},{},{},{},{},{},{}],[{},{},{"id":10,"wormhole":"wormholeEnd"},{"id":11,"note":"do","obstacle":"hor"},{},{},{"id":14,"note":"sol","obstacle":"vert"},{}],[{},{},{"id":18,"obstacle":"forward"},{"id":19,"obstacle":"forward","note":"sol"},{"id":20,"start":"right"},{"id":21,"note":"_do"},{"id":22,"wormhole":"wormholeStart"},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],["do"],["sol"],["do"],[],["_do"],[],["sol"],[],[],["sol"],[],[],["do"],[]],"viewportOffset":[100,0]}',
	10: '{"number":"10","author":"Chris","size":[8,4],"wormholeStart":[5,2],"wormholeEnd":[2,1],"level":[[{},{},{},{},{},{},{},{}],[{},{},{"id":10,"wormhole":"wormholeEnd"},{"id":11,"obstacle":"backGate","note":"_do"},{"id":12,"obstacle":"hor"},{"id":13,"obstacle":"back"},{},{}],[{},{},{"id":18,"obstacle":"forGate"},{"id":19,"start":"right"},{"id":20,"obstacle":"vertGate","note":"sol"},{"id":21,"wormhole":"wormholeStart"},{},{}],[{},{},{"id":26,"obstacle":"back","note":"sol"},{"id":27,"obstacle":"hor"},{"id":28,"obstacle":"backGate"},{"id":29,"obstacle":"forward","note":"do"},{},{}]],"solution":[["sol"],[],["_do"],[],[],["sol"],[],[],["sol"],[],["_do"],[],["sol"],[],["do"],[]],"viewportOffset":[0,100]}',
	///////////////////
	//fa introduced
	///////////////////
	11: '{"number":"11","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{},{},{},{},{}],[{},{},{},{"id":11,"note":"sol","obstacle":"forward"},{"id":12,"obstacle":"back"},{"id":13,"note":"do","obstacle":"back"},{},{}],[{},{},{"id":18,"start":"right"},{"id":19,"note":"_do"},{"id":20,"obstacle":"forward"},{"id":21,"note":"fa"},{},{}],[{},{},{},{"id":27,"obstacle":"back"},{"id":28,"note":"sol","obstacle":"back"},{"id":29,"obstacle":"forward"},{},{}]],"solution":[["_do"],[],["sol"],[],["fa"],["do"],[],[],["fa"]],"viewportOffset":[100,100]}',
	12: '{"number":"12","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{},{},{},{},{}],[{},{},{"id":10,"note":"sol","obstacle":"forward"},{},{"id":12,"obstacle":"back"},{},{},{}],[{},{},{"id":18,"obstacle":"backGate"},{"id":19,"start":"right"},{"id":20,"note":"_do","obstacle":"forward"},{},{},{}],[{},{},{"id":26,"obstacle":"back"},{"id":27,"note":"fa"},{"id":28,"obstacle":"forward"},{},{},{}]],"solution":[["_do"],[],[],["sol"],[],[],["_do"],[],["_do"],[],[],["sol"],[],[],["fa"],[]],"viewportOffset":[-100,100]}',
	13: '{"number":"13","author":"Chris","size":[8,4],"wormholeStart":[2,1],"wormholeEnd":[4,2],"level":[[{},{},{},{},{},{},{},{}],[{},{},{"id":10,"wormhole":"wormholeStart"},{"id":11,"note":"fa"},{"id":12,"obstacle":"back"},{},{},{}],[{},{"id":17,"start":"right"},{"id":18,"note":"_do","obstacle":"forGate"},{"id":19,"obstacle":"forward"},{"id":20,"wormhole":"wormholeEnd"},{},{},{}],[{},{},{"id":26,"obstacle":"back"},{"id":27,"obstacle":"forward","note":"sol"},{},{},{},{}]],"solution":[["_do"],[],[],[],["_do"],[],["sol"],[],["fa"]],"viewportOffset":[-100,100]}',
	14: ' ',
	//interactions between obstacles and wormholes introduced
	15: '{"number":"15","author":"Chris","size":[8,4],"wormholeStart":[2,1],"wormholeEnd":[6,2],"level":[[{},{},{},{},{},{},{},{}],[{},{"id":9,"start":"right"},{"id":10,"wormhole":"wormholeStart","obstacle":"vert"},{"id":11,"note":"do"},{},{"id":13,"note":"_do"},{"id":14,"obstacle":"back"},{}],[{},{},{"id":18,"obstacle":"back"},{"id":19,"note":"sol"},{},{"id":21,"note":"_do"},{"id":22,"wormhole":"wormholeEnd","obstacle":"vert"},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],["sol"],[],["sol"],[],["_do"],[],["do"],[],["_do"]],"viewportOffset":[0,0]}',
	//interaction between notes and wormholes introduced
	16: '{"number":"16","author":"Chris","size":[8,4],"wormholeStart":[4,0],"wormholeEnd":[5,3],"level":[[{},{},{},{"id":3,"obstacle":"forward"},{"id":4,"wormhole":"wormholeStart","note":"sol"},{"id":5,"obstacle":"back"},{},{}],[{},{},{},{"id":11,"obstacle":"vert"},{"id":12,"obstacle":"back"},{"id":13,"note":"_do"},{},{}],[{},{},{"id":18,"start":"right"},{"id":19,"note":"fa"},{"id":20,"obstacle":"back"},{"id":21,"obstacle":"forward"},{},{}],[{},{},{},{"id":27,"obstacle":"back"},{"id":28,"obstacle":"hor"},{"id":29,"wormhole":"wormholeEnd","note":"do"},{},{}]],"solution":[["fa"],[],[],["_do"],[],["sol"],[],["do"],[],["_do"],[],[],["fa"]],"viewportOffset":[100,0]}',
	17: '{"number":"17","author":"Chris","size":[8,4],"wormholeStart":[5,2],"wormholeEnd":[3,1],"level":[[{},{},{},{"id":3,"obstacle":"forward","note":"do"},{},{"id":5,"obstacle":"back"},{},{}],[{},{},{},{"id":11,"wormhole":"wormholeEnd","obstacle":"forGate"},{},{"id":13,"obstacle":"forward","note":"sol"},{},{}],[{},{},{},{"id":19,"obstacle":"forward","note":"fa"},{"id":20,"start":"right"},{"id":21,"wormhole":"wormholeStart","obstacle":"forGate"},{},{}],[{},{},{},{"id":27,"obstacle":"back"},{},{"id":29,"obstacle":"forward","note":"fa"},{},{}]],"solution":[["sol"],[],[],["fa"],[],["do"],[],[],["sol"],[],["fa"]],"viewportOffset":[100,0]}',
	//looping melodies introduced
	18: '{"number":"18","author":"Chris","size":[8,4],"wormholeStart":[3,2],"wormholeEnd":[6,1],"level":[[{},{},{},{},{"id":4,"note":"sol","obstacle":"forward"},{"id":5,"obstacle":"forGate"},{"id":6,"note":"fa","obstacle":"back"},{}],[{},{},{"id":10,"start":"right"},{"id":11,"note":"_do","obstacle":"hor"},{"id":12,"obstacle":"backGate"},{"id":13,"obstacle":"back"},{"id":14,"wormhole":"wormholeEnd","obstacle":"vert"},{}],[{},{},{},{"id":19,"wormhole":"wormholeStart","obstacle":"hor"},{"id":20,"obstacle":"back"},{"id":21,"note":"do","obstacle":"backGate"},{"id":22,"obstacle":"forward"},{}],[{},{},{},{"id":27,"note":"sol","obstacle":"back"},{"id":28,"obstacle":"forGate"},{"id":29,"obstacle":"forward"},{},{}]],"solution":[["_do"],[],[],["do"],[],[],["sol"],[],["fa"],[],[],[],["_do"],[],[],["do"],[],[],["sol"],[],["fa"],[]],"viewportOffset":[200,0]}',
	19: '{"number":"19","author":"Chris","size":[8,4],"wormholeStart":[4,1],"wormholeEnd":[3,2],"level":[[{},{},{"id":2,"obstacle":"forward"},{"id":3,"obstacle":"forward"},{"id":4,"obstacle":"back"},{"id":5,"obstacle":"back"},{},{}],[{},{},{"id":10,"obstacle":"forward"},{"id":11,"start":"right","note":"sol"},{"id":12,"wormhole":"wormholeStart","obstacle":"vertGate"},{"id":13,"obstacle":"back","note":"_do"},{},{}],[{},{},{"id":18,"obstacle":"back"},{"id":19,"wormhole":"wormholeEnd","obstacle":"vertGate"},{"id":20,"note":"fa"},{"id":21,"obstacle":"forward"},{},{}],[{},{},{"id":26,"obstacle":"back"},{"id":27,"obstacle":"back","note":"do"},{"id":28,"obstacle":"forward"},{"id":29,"obstacle":"forward"},{},{}]],"solution":[["fa"],[],[],[],["do"],[],[],[],["_do"],[],[],[],["sol"],[],["fa"],[],[],[],["do"],[],[],[],["_do"],[],[],[],["sol"],[],["fa"]],"viewportOffset":[0,0]}',
	//'Futurama'
	20: '{"number":"20","author":"Chris","size":[8,4],"wormholeStart":[5,2],"wormholeEnd":[2,1],"level":[[{},{},{},{},{"id":4,"start":"down"},{"id":5,"obstacle":"forward"},{"id":6,"obstacle":"back"},{}],[{},{},{"id":10,"wormhole":"wormholeEnd"},{"id":11,"obstacle":"back"},{"id":12,"note":"sol","twoTone":null,"obstacle":"back"},{"id":13,"note":"sol","twoTone":null,"obstacle":"forGate"},{"id":14,"note":"fa","twoTone":null,"obstacle":"forward"},{}],[{},{},{"id":18,"obstacle":"vert"},{"id":19,"note":"sol","twoTone":null,"obstacle":"forward"},{"id":20,"obstacle":"backGate"},{"id":21,"note":"sol","twoTone":null,"wormhole":"wormholeStart","obstacle":"hor"},{"id":22,"obstacle":"back"},{}],[{},{},{"id":26,"obstacle":"back"},{"id":27,"note":"do","twoTone":null},{"id":28,"note":"do","twoTone":null,"obstacle":"forward"},{"id":29,"obstacle":"forGate"},{"id":30,"note":"fa","twoTone":null,"obstacle":"forward"},{}]],"solution":[["sol"],[],["sol"],[],[],["do"],["do"],[],["fa"],[],["fa"],[],[],["sol"],["sol"],[],["sol"],[],["sol"],[],[],["do"],["do"],[],["fa"],[],["fa"],[],[],["sol"],["sol"]],"viewportOffset":[100,0], "bps":4}',
	//two-tones introduced
	21: '{"number":"21","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{},{},{},{},{}],[{},{},{"id":10,"twoTone":null,"obstacle":"forward","note":"_do"},{"id":11,"start":"left"},{"id":12,"obstacle":"back"},{},{},{}],[{},{},{},{},{"id":20,"twoTone":["_do","do"],"note":null},{},{},{}],[{},{},{"id":26,"note":"sol","obstacle":"back","twoTone":null},{},{"id":28,"obstacle":"forward"},{},{},{}]],"solution":[["_do"],[],[],["do"],[],[],["sol"],[],["_do"]],"viewportOffset":[-100,100]}',
	22: '{"number":"22","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{"id":3,"obstacle":"forward"},{"id":4,"twoTone":["fa","do"],"note":null,"obstacle":"back"},{},{},{}],[{},{},{"id":10,"start":"right"},{"id":11,"obstacle":"backGate"},{"id":12,"obstacle":"forGate"},{},{},{}],[{},{},{},{"id":19,"twoTone":["_do","sol"],"note":null},{},{},{},{}],[{},{},{},{"id":27,"obstacle":"back"},{"id":28,"obstacle":"forward","note":"fa","twoTone":null},{},{},{}]],"solution":[["do"],[],[],["fa"],[],["sol"],[],[],["fa"]],"viewportOffset":[0,0]}',
	23: '{"number":"23","author":"Chris","size":[8,4],"wormholeStart":[3,2],"wormholeEnd":[5,2],"level":[[{},{},{},{},{},{},{},{}],[{},{},{},{"id":11,"obstacle":"forward"},{"id":12,"obstacle":"forGate","note":"sol","twoTone":null},{"id":13,"obstacle":"hor"},{"id":14,"obstacle":"back"},{}],[{},{},{"id":18,"start":"right"},{"id":19,"wormhole":"wormholeStart"},{"id":20,"twoTone":["_do","do"],"note":null,"obstacle":"hor"},{"id":21,"wormhole":"wormholeEnd"},{"id":22,"obstacle":"forward","note":"_do","twoTone":null},{}],[{},{},{},{"id":27,"obstacle":"back"},{"id":28,"obstacle":"backGate","note":"fa","twoTone":null},{"id":29,"obstacle":"hor"},{"id":30,"obstacle":"forward"},{}]],"solution":[["_do"],[],[],["fa"],[],[],[],["sol"],["do"],[],["_do"],["fa"]],"viewportOffset":[200,100]}',
	24: '{"number":"24","author":"Chris","size":[8,4],"wormholeStart":[4,2],"wormholeEnd":[2,1],"level":[[{},{},{},{"id":3,"obstacle":"forward"},{"id":4,"note":"fa","twoTone":null,"obstacle":"backGate"},{},{},{}],[{},{"id":9,"obstacle":"forward","twoTone":null,"note":"sol"},{"id":10,"wormhole":"wormholeEnd"},{"id":11,"obstacle":"back","twoTone":["do","sol"],"note":null},{"id":12,"obstacle":"forward"},{"id":13,"obstacle":"back","note":"_do","twoTone":null},{},{}],[{},{"id":17,"obstacle":"back"},{"id":18,"start":"right"},{"id":19,"note":null,"twoTone":["_do","sol"],"obstacle":"backGate"},{"id":20,"wormhole":"wormholeStart"},{"id":21,"obstacle":"forward"},{},{}],[{},{},{"id":26,"note":"fa","twoTone":null,"obstacle":"backGate"},{"id":27,"obstacle":"forward"},{},{},{},{}]],"solution":[["sol"],[],["fa"],[],[],[],["_do"],[],[],["sol"],[],[],["_do"],[],["sol"],[],["fa"]],"viewportOffset":[-100,0]}',
	25: '{"number":"25","author":"Chris","size":[8,4],"wormholeStart":[4,1],"wormholeEnd":[3,2],"level":[[{},{},{"id":2,"obstacle":"forward"},{"id":3,"obstacle":"forward","note":"_do","twoTone":null},{"id":4,"obstacle":"back"},{"id":5,"obstacle":"back"},{},{}],[{},{},{"id":10,"obstacle":"forward"},{"id":11,"start":"right"},{"id":12,"wormhole":"wormholeStart","obstacle":"vertGate"},{"id":13,"obstacle":"back"},{},{}],[{},{},{"id":18,"obstacle":"back","note":"do","twoTone":null},{"id":19,"wormhole":"wormholeEnd","obstacle":"vertGate"},{"id":20,"twoTone":["sol","fa"],"note":null},{"id":21,"obstacle":"forward","note":null,"twoTone":["fa","sol"]},{},{}],[{},{},{"id":26,"obstacle":"back"},{"id":27,"obstacle":"back","note":"fa","twoTone":null},{"id":28,"obstacle":"forward"},{"id":29,"obstacle":"forward"},{},{}]],"solution":[["do"],[],["fa"],[],[],["_do"],[],[],["fa"],[],[],["sol"],[],[],["do"],[],["fa"],[],[],["_do"],[],[],["sol"],[],[],["fa"],[]],"viewportOffset":[0,0]}',
	////////////////
	//mi introduced
	////////////////
	26: '{"number":"26","author":"Chris","size":[8,4],"level":[[{},{},{},{},{},{},{},{}],[{},{"id":9,"start":"right"},{"id":10,"note":"_do","twoTone":null},{},{"id":12,"note":"mi","twoTone":null,"obstacle":"back"},{"id":13,"note":"fa","twoTone":null,"obstacle":"backGate"},{},{"id":15,"note":"do","twoTone":null,"obstacle":"back"}],[{},{},{"id":18,"note":"do","twoTone":null,"obstacle":"vert"},{},{"id":20,"note":"fa","twoTone":null,"obstacle":"backGate"},{"id":21,"note":"mi","twoTone":null,"obstacle":"back"},{},{"id":23,"note":"_do","twoTone":null,"obstacle":"vert"}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],["mi"],["fa"],["mi"],[],["_do"],["do"],[],["fa"],["mi"],[],["_do"],[],[]],"viewportOffset":[200,0],"wormholeStart":null,"wormholeEnd":null}',
	27: '{"number":"27","author":"Chris","size":[8,4],"wormholeStart":[4,1],"wormholeEnd":[3,2],"level":[[{},{},{},{},{},{},{},{}],[{},{},{"id":10,"start":"right"},{"id":11,"note":"_do","twoTone":null,"obstacle":"backGate"},{"id":12,"wormhole":"wormholeStart","obstacle":"forGate"},{"id":13,"note":"do","twoTone":null,"obstacle":"vert"},{},{}],[{},{},{},{"id":19,"wormhole":"wormholeEnd","obstacle":"forGate"},{"id":20,"note":"mi","twoTone":null,"obstacle":"forward"},{"id":21,"obstacle":"hor"},{},{}],[{},{},{},{"id":27,"note":"sol","twoTone":null,"obstacle":"hor"},{"id":28,"obstacle":"vert"},{},{},{}]],"solution":[["_do"],[],["mi"],[],["do"],[],["sol"],[],["mi"],[],["_do"]],"viewportOffset":[100,100]}',
	//'Oh, When the Saints'
	28: '{"number":"28","author":"Chris","size":[8,4],"wormholeStart":[2,2],"wormholeEnd":[4,0],"level":[[{},{},{"id":2,"obstacle":"forward"},{"id":3,"note":"mi","twoTone":null,"obstacle":"hor"},{"id":4,"wormhole":"wormholeEnd"},{"id":5,"obstacle":"back"},{},{}],[{},{"id":9,"start":"right"},{"id":10,"note":null,"twoTone":["_do","mi"],"obstacle":"back"},{"id":11,"obstacle":"backGate"},{"id":12,"note":null,"twoTone":["_do","fa"],"obstacle":"backGate"},{"id":13,"obstacle":"forward"},{},{}],[{},{"id":17,"obstacle":"forward"},{"id":18,"wormhole":"wormholeStart"},{"id":19,"note":"sol","twoTone":null,"obstacle":"forGate"},{"id":20,"obstacle":"hor"},{},{},{}],[{},{"id":25,"obstacle":"back"},{},{"id":27,"obstacle":"vert"},{},{},{},{}]],"solution":[["_do"],[],["mi"],[],["fa"],[],["sol"],[],[],[],[],[],[],[],["_do"],[],["mi"],[],["fa"],[],["sol"],[]],"viewportOffset":[-100,0]}',
	29: '{"number":"29","author":"Chris","size":[8,4],"wormholeStart":[1,2],"wormholeEnd":[5,2],"level":[[{},{},{},{},{},{},{},{}],[{},{"id":9,"obstacle":"forward","note":"sol","twoTone":null},{},{"id":11,"obstacle":"backGate","note":"_do","twoTone":null},{"id":12,"obstacle":"hor"},{"id":13,"note":"mi","twoTone":null,"obstacle":"back"},{},{}],[{},{"id":17,"wormhole":"wormholeStart","obstacle":"forward"},{"id":18,"start":"right"},{"id":19,"note":"mi","twoTone":null},{"id":20,"obstacle":"backGate"},{"id":21,"wormhole":"wormholeEnd","obstacle":"forward"},{},{}],[{},{"id":25,"obstacle":"back","note":"_do","twoTone":null},{},{"id":27,"obstacle":"forward"},{"id":28,"note":"fa","twoTone":null,"obstacle":"forward"},{"id":29,"note":"_do","twoTone":null,"obstacle":"hor"},{},{}]],"solution":[["mi"],[],["fa"],[],[],["_do"],[],["sol"],[],["_do"],["fa"],[],["mi"],["_do"],[]],"viewportOffset":[-100,100]}',
	//'Imperial March'
	30: '{"number":"30","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{"id":4,"obstacle":"forward","note":"_do","twoTone":null},{"id":5,"obstacle":"backGate"},{"id":6,"obstacle":"hor"},{"id":7,"wormhole":"wormholeEnd","obstacle":"horGate"},{},{}],[{},{},{"id":12,"obstacle":"backGate"},{"id":13,"start":"down"},{"id":14,"obstacle":"hor"},{"id":15,"obstacle":"forGate"},{},{}],[{},{},{"id":20,"obstacle":"forGate"},{"id":21,"obstacle":"vert"},{"id":22,"note":"mi","twoTone":null,"obstacle":"backGate"},{"id":23,"obstacle":"hor"},{},{}],[{},{},{"id":28,"obstacle":"hor","note":"sol","twoTone":null},{"id":29,"note":"mi","twoTone":null,"obstacle":"back"},{"id":30,"wormhole":"wormholeStart","obstacle":"back"},{},{},{}]],"solution":[["mi"],[],[],[],["mi"],[],[],[],["mi"],[],[],[],["_do"],[],[],["sol"],["mi"],[],[],[],["_do"],[],[],["sol"],["mi"],[]],"viewportOffset":[0,0]}',
	//double-start levels introduced
	31: '{"number":"31","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{"id":3,"obstacle":"forward"},{"id":4,"note":"mi","twoTone":null},{"id":5,"obstacle":"back"},{},{}],[{},{},{"id":10,"obstacle":"hor","note":"_do","twoTone":null},{},{"id":12,"obstacle":"back","note":"sol","twoTone":null},{"id":13,"start":"down"},{},{}],[{},{},{"id":18,"start":"up"},{"id":19,"obstacle":"back","note":"sol","twoTone":null},{},{"id":21,"obstacle":"hor","note":"_do","twoTone":null},{},{}],[{},{},{"id":26,"obstacle":"back"},{"id":27,"note":"mi","twoTone":null},{"id":28,"obstacle":"forward"},{},{},{}]],"solution":[["_do"],[],["sol"],[],[],["mi"],[],["mi"],[],[],["sol"],[],["_do"]],"viewportOffset":[0,0]}',
	32: '{"number":"32","author":"Chris","size":[8,4],"wormholeStart":[1,1],"wormholeEnd":[6,2],"level":[[{},{},{"id":2,"obstacle":"forward"},{"id":3,"obstacle":"back"},{"id":4,"twoTone":["do","sol"],"note":null,"obstacle":"back"},{},{},{}],[{},{"id":9,"wormhole":"wormholeStart"},{"id":10,"note":null,"twoTone":["fa","_do"]},{"id":11,"obstacle":"back"},{"id":12,"obstacle":"forward"},{"id":13,"start":"down"},{},{}],[{},{},{"id":18,"start":"up"},{"id":19,"obstacle":"forward"},{"id":20,"obstacle":"back"},{"id":21,"note":null,"twoTone":["fa","_do"]},{"id":22,"wormhole":"wormholeEnd"},{}],[{},{},{},{"id":27,"twoTone":["do","sol"],"note":null,"obstacle":"back"},{"id":28,"obstacle":"back"},{"id":29,"obstacle":"forward"},{},{}]],"solution":[["_do"],[],[],["do"],[],[],["fa"],[],["_do"],[],[],["sol"],[],[],["fa"]],"viewportOffset":[0,0]}',
	33: '{"number":"33","author":"Chris","size":[8,4],"wormholeStart":[0,0],"wormholeEnd":[7,3],"level":[[{"id":0,"wormhole":"wormholeStart","note":"do"},{"id":1,"obstacle":"hor"},{},{},{},{},{},{}],[{"id":8,"obstacle":"vert"},{"id":9,"obstacle":"backGate"},{},{"id":11,"note":"_do"},{"id":12,"start":"left"},{},{"id":14,"obstacle":"vert","note":"sol"},{}],[{},{"id":17,"obstacle":"vert","note":"sol"},{},{"id":19,"start":"right"},{"id":20,"note":"_do"},{},{"id":22,"obstacle":"backGate"},{"id":23,"obstacle":"vert"}],[{},{},{},{},{},{},{"id":30,"obstacle":"hor"},{"id":31,"wormhole":"wormholeEnd","note":"do"}]],"solution":[["_do"],[],[],[],["do"],[],[],[],["_do"],[],[],["sol"],[],[],["do"],[],[],["sol"],[],[],["_do"]],"viewportOffset":[0,0]}',
	34: '{"number":"34","author":"Chris","size":[8,4],"wormholeStart":[0,2],"wormholeEnd":[6,0],"level":[[{"id":0,"obstacle":"forward","note":null,"twoTone":["_do","do"]},{"id":1,"obstacle":"forward"},{"id":2,"note":"sol","twoTone":null},{"id":3,"start":"down"},{},{"id":5,"obstacle":"back","note":null,"twoTone":["fa","mi"]},{"id":6,"wormhole":"wormholeEnd"},{}],[{"id":8,"obstacle":"forward","note":"mi","twoTone":null},{"id":9,"obstacle":"forGate"},{},{"id":11,"obstacle":"back","note":"_do","twoTone":null},{},{"id":13,"obstacle":"forGate"},{"id":14,"obstacle":"forward","note":"mi","twoTone":null},{}],[{"id":16,"wormhole":"wormholeStart"},{"id":17,"obstacle":"back","note":null,"twoTone":["fa","mi"]},{},{"id":19,"start":"up"},{"id":20,"note":"sol","twoTone":null},{"id":21,"obstacle":"forward"},{"id":22,"obstacle":"forward","note":null,"twoTone":["_do","do"]},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],[],["mi"],[],["fa"],[],[],["do"],["mi"],[],[],["_do"],[]],"viewportOffset":[-100,-100]}',
	///////////////////
	//fi introduced
	///////////////////
	35: '{"number":"35","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{"id":0,"start":"right"},{"id":1,"note":"_do","twoTone":null},{"id":2,"obstacle":"back"},{"id":3,"note":"sol","twoTone":null,"obstacle":"backGate"},{"id":4,"obstacle":"back"},{},{},{}],[{},{},{"id":10,"note":"mi","twoTone":null,"obstacle":"back"},{"id":11,"note":"fi","twoTone":null},{"id":12,"obstacle":"back"},{"id":13,"obstacle":"back"},{},{}],[{},{},{"id":18,"obstacle":"back"},{"id":19,"obstacle":"back"},{"id":20,"note":"fi","twoTone":null},{"id":21,"note":"mi","twoTone":null,"obstacle":"back"},{},{}],[{},{},{},{"id":27,"obstacle":"back"},{"id":28,"note":"sol","twoTone":null,"obstacle":"backGate"},{"id":29,"obstacle":"back"},{"id":30,"note":"_do","twoTone":null},{"id":31,"start":"left"}]],"solution":[["_do"],[],["sol"],["fi"],[],[],["mi"],["fi"],[],[],["sol"],[],["_do"]],"viewportOffset":[0,0]}',
	//asymmetrical double-start levels introduced
	36: '{"number":"36","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{"id":2,"obstacle":"back","twoTone":["sol","fa"],"note":null},{},{"id":4,"obstacle":"forward"},{},{},{}],[{},{},{},{"id":11,"obstacle":"forward"},{"id":12,"start":"left"},{"id":13,"obstacle":"back"},{},{}],[{},{},{"id":18,"obstacle":"forward"},{"id":19,"start":"right","note":"_do","twoTone":null},{"id":20,"obstacle":"back"},{"id":21,"note":"fi","twoTone":null},{},{}],[{},{},{},{"id":27,"obstacle":"back"},{},{"id":29,"obstacle":"forward"},{},{}]],"solution":[["_do"],[],[],["fa"],["fi"],[],[],["sol"],["_do"],[]],"viewportOffset":[0,0]}',
	37: '{"number":"37","author":"Chris","size":[8,4],"wormholeStart":[4,1],"wormholeEnd":[3,2],"level":[[{},{},{"id":2,"obstacle":"forward","note":"do","twoTone":null},{"id":3,"obstacle":"forward"},{"id":4,"obstacle":"back"},{"id":5,"obstacle":"back"},{},{}],[{},{},{"id":10,"obstacle":"forward"},{"id":11,"start":"right"},{"id":12,"obstacle":"back","wormhole":"wormholeStart","note":"_do","twoTone":null},{"id":13,"obstacle":"back"},{},{}],[{},{},{"id":18,"obstacle":"back"},{"id":19,"obstacle":"back","wormhole":"wormholeEnd","note":"sol","twoTone":null},{"id":20,"start":"down"},{"id":21,"obstacle":"forward","note":"fi","twoTone":null},{},{}],[{},{},{"id":26,"obstacle":"back"},{"id":27,"obstacle":"back"},{"id":28,"obstacle":"forward"},{"id":29,"obstacle":"forward"},{},{}]],"solution":[["_do"],[],["fi"],["do"],["sol"],[],["_do"],[],["fi"],["do"],["sol"],[],["_do"]],"viewportOffset":[0,0]}',
	38: '{"number":"38","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{"id":0,"obstacle":"forward"},{"id":1,"note":"do","twoTone":null,"obstacle":"forward"},{"id":2,"obstacle":"back"},{"id":3,"obstacle":"back","note":"fa","twoTone":null},{"id":4,"obstacle":"forward"},{"id":5,"obstacle":"forward"},{"id":6,"obstacle":"back","note":"sol","twoTone":null},{"id":7,"obstacle":"back"}],[{"id":8,"obstacle":"forward","note":"fa","twoTone":null},{"id":9,"start":"up"},{"id":10,"obstacle":"back"},{"id":11,"obstacle":"back"},{"id":12,"note":"fi","twoTone":null,"obstacle":"forward"},{"id":13,"obstacle":"forward"},{"id":14,"obstacle":"back"},{"id":15,"obstacle":"back","note":"fa","twoTone":null}],[{"id":16,"obstacle":"back"},{"id":17,"obstacle":"back"},{"id":18,"obstacle":"forward","note":"fa","twoTone":null},{"id":19,"note":"do","twoTone":null,"obstacle":"forward"},{"id":20,"obstacle":"back","note":"mi","twoTone":null},{"id":21,"obstacle":"back"},{"id":22,"start":"down"},{"id":23,"obstacle":"forward"}],[{"id":24,"note":"do","twoTone":null,"obstacle":"back"},{"id":25,"obstacle":"back","note":"fa","twoTone":null},{"id":26,"obstacle":"forward"},{"id":27,"obstacle":"forward"},{"id":28,"obstacle":"back"},{"id":29,"obstacle":"back"},{"id":30,"obstacle":"forward","note":"_do","twoTone":null},{"id":31,"obstacle":"forward"}]],"solution":[["do","_do"],[],[],["mi"],["do"],[],["fi"],[],["do"],["sol"],[],[],["do","_do"],[],[],["mi"],["do"],[],["fi"],[],["do"],["sol"],[],[],["do","_do"]],"viewportOffset":[0,0]}',
	39: '{"number":"39","author":"Chris","size":[8,4],"wormholeStart":[3,2],"wormholeEnd":[7,0],"level":[[{"id":0,"obstacle":"forward"},{"id":1,"obstacle":"forGate"},{"id":2,"obstacle":"forward","note":"sol","twoTone":null},{"id":3,"obstacle":"back"},{"id":4,"note":"fi","twoTone":null},{"id":5,"obstacle":"forward"},{"id":6,"obstacle":"back"},{"id":7,"obstacle":"hor","wormhole":"wormholeEnd","note":"sol","twoTone":null}],[{"id":8,"obstacle":"vert","note":"sol","twoTone":null},{"id":9,"note":"sol","twoTone":null},{"id":10,"start":"up"},{"id":11,"note":"mi","twoTone":null},{"id":12,"obstacle":"back"},{"id":13,"note":"sol","twoTone":null,"obstacle":"forGate"},{"id":14,"obstacle":"forward"},{"id":15,"note":"sol","twoTone":null}],[{},{"id":17,"obstacle":"backGate"},{"id":18,"obstacle":"back"},{"id":19,"obstacle":"forward","wormhole":"wormholeStart"},{},{"id":21,"start":"up"},{"id":22,"obstacle":"hor","note":"fi","twoTone":null},{"id":23,"obstacle":"back"}],[{"id":24,"obstacle":"back"},{"id":25,"obstacle":"vert","note":"sol","twoTone":null},{"id":26,"obstacle":"hor"},{"id":27,"obstacle":"horGate"},{"id":28,"obstacle":"hor","note":"sol","twoTone":null},{"id":29,"obstacle":"hor","note":"mi","twoTone":null},{"id":30,"obstacle":"back"},{"id":31,"note":"mi","twoTone":null,"obstacle":"forward"}]],"solution":[["sol"],[],["fi"],["sol"],["mi"],[],["sol"],[],["fi"],["sol"],["mi"],[],["sol"],[],["fi"],["sol"],["mi"],[],["sol"],[],["fi"],["sol"],["mi"],[]],"viewportOffset":[0,0], "bps":5}',
	//buttons introduced
	40: '{"number":"40","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{},{},{},{},{}],[{},{},{"id":10,"obstacle":"forward"},{"id":11,"note":"do","twoTone":null,"obstacle":"forward"},{"id":12,"button":["6"]},{"id":13,"obstacle":"back"},{},{}],[{},{},{"id":18,"note":"sol","twoTone":null,"obstacle":"vert"},{"id":19,"obstacle":"backGate"},{},{"id":21,"obstacle":"forward","note":"fi","twoTone":null},{},{}],[{},{},{},{"id":27,"start":"up","note":"_do","twoTone":null},{},{},{},{}]],"solution":[["sol"],[],["do"],[],[],["fi"],[],[],["do"],[],["_do"]],"viewportOffset":[0,100]}',
	41: '{"number":"41","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{"id":2,"obstacle":"hor"},{},{"id":4,"note":"sol","twoTone":null},{"id":5,"obstacle":"back"},{},{}],[{},{"id":9,"start":"right"},{"id":10,"obstacle":"forGate"},{"id":11,"button":["3","2"]},{"id":12,"obstacle":"backGate"},{"id":13,"obstacle":"back"},{},{}],[{},{},{"id":18,"obstacle":"back","note":"mi","twoTone":null},{},{"id":20,"obstacle":"hor"},{"id":21,"obstacle":"forward","note":"fi","twoTone":null},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["sol"],[],[],["fi"],[],[],["sol"],[],["mi"],[],[],[],["sol"],[],[],["fi"],[],[],["sol"]],"viewportOffset":[0,-100]}',
	42: '{"number":"42","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{},{},{},{},{}],[{},{},{"id":10,"obstacle":"hor","twoTone":["fi","mi"],"note":null},{},{"id":12,"note":"sol","twoTone":null,"obstacle":"back"},{},{},{}],[{},{},{},{"id":19,"button":["0"]},{"id":20,"start":"up"},{},{},{}],[{},{},{"id":26,"obstacle":"back"},{"id":27,"button":["1"]},{"id":28,"obstacle":"forward"},{},{},{}]],"solution":[["sol"],[],[],["mi"],[],[],["fi"],[],[],["mi"],[],[],["sol"],[],[],["fi"],[],[],["mi"]],"viewportOffset":[-100,100]}',
	43: '{"number":"43","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{"id":0,"obstacle":"forward"},{"id":1,"note":null,"twoTone":["_do","do"]},{"id":2,"obstacle":"forward"},{"id":3,"button":["7"]},{"id":4,"obstacle":"back"},{"id":5,"note":"fi","twoTone":null},{"id":6,"obstacle":"back"},{}],[{"id":8,"start":"down"},{"id":9,"button":["1"]},{"id":10,"obstacle":"forGate"},{"id":11,"button":["7"]},{"id":12,"obstacle":"backGate"},{"id":13,"button":["1"]},{"id":14,"obstacle":"forward"},{}],[{"id":16,"obstacle":"back"},{"id":17,"button":["1","2"]},{"id":18,"obstacle":"hor"},{"id":19,"note":null,"twoTone":["mi","sol"]},{"id":20,"obstacle":"hor"},{"id":21,"button":["1","0"]},{"id":22,"obstacle":"forward"},{}],[{},{},{},{},{},{},{},{}]],"solution":[["do"],[],[],[],["mi"],[],[],[],["fi"],[],[],["fi"],[],[],["sol"],[],[],[],["_do"],[],[],[],["do"]],"viewportOffset":[-100,-100]}',
	44: '{"number":"44","author":"Chris","size":[11,5],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{},{"id":4,"obstacle":"hor"},{},{},{},{},{},{}],[{},{},{},{"id":14,"note":null,"twoTone":["_do","sol"]},{"id":15,"button":["7","5"]},{"id":16,"note":null,"twoTone":["mi","fa"]},{},{},{},{},{}],[{},{"id":23,"start":"right"},{"id":24,"obstacle":"hor"},{"id":25,"button":["5","1","3"]},{"id":26,"obstacle":"back"},{"id":27,"button":["3","7"]},{"id":28,"obstacle":"vert"},{},{},{},{}],[{},{},{},{"id":36,"note":null,"twoTone":["sol","do"]},{"id":37,"button":["1","3"]},{"id":38,"note":null,"twoTone":["fi","sol"]},{},{},{},{},{}],[{},{},{},{},{"id":48,"obstacle":"hor"},{},{},{},{},{},{}]],"solution":[["sol"],[],["sol"],[],["do"],[],["sol"],[],["fi"],[],["fa"],[],["mi"],[],["_do"],[],["sol"],[],["sol"],[],["do"],[],["sol"],[],["fi"],[],["fa"],[],["mi"],[],["_do"]],"viewportOffset":[-200,0]}',
	45: '{"number":"45","author":"Chris","size":[8,4],"wormholeStart":[6,1],"wormholeEnd":[0,1],"level":[[{"id":0,"note":"mi","twoTone":null,"obstacle":"forward"},{},{"id":2,"note":"fa","twoTone":null},{"id":3,"note":"sol","twoTone":null},{},{"id":5,"button":["8"]},{"id":6,"note":"_do","twoTone":null,"obstacle":"back"},{}],[{"id":8,"wormhole":"wormholeEnd"},{"id":9,"note":"sol","twoTone":null},{},{},{"id":12,"note":"do","twoTone":null,"start":"right"},{"id":13,"button":["5"]},{"id":14,"wormhole":"wormholeStart","obstacle":"hor"},{}],[{"id":16,"note":"mi","twoTone":null,"obstacle":"back"},{},{"id":18,"note":"fa","twoTone":null},{"id":19,"note":"sol","twoTone":null},{},{"id":21,"button":["2"]},{"id":22,"note":"fa","twoTone":null,"obstacle":"forward"},{}],[{},{},{},{},{},{},{},{}]],"solution":[["sol"],[],[],["do"],[],[],["mi"],[],["fa"],["sol"],[],[],["fa"],[],["mi"],[],["fa"],[],[],["sol"],["fa"],[],["mi"],[],["_do"],[]],"viewportOffset":[-100,-100]}',
	46: '{"number":"46","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{"id":0,"obstacle":"forward"},{"id":1,"obstacle":"back","note":"_do","twoTone":null},{"id":2,"obstacle":"back"},{},{"id":4,"obstacle":"forward"},{"id":5,"obstacle":"back","note":"sol","twoTone":null},{"id":6,"obstacle":"back"},{}],[{"id":8,"obstacle":"vert"},{},{"id":10,"obstacle":"backGate"},{"id":11,"obstacle":"back","note":"mi","twoTone":null},{"id":12,"obstacle":"forward"},{"id":13,"button":["7"]},{"id":14,"start":"down","note":"fi","twoTone":null},{"id":15,"obstacle":"back"}],[{"id":16,"obstacle":"back"},{"id":17,"note":"fi","twoTone":null,"start":"up"},{"id":18,"button":["1"]},{"id":19,"obstacle":"forward"},{"id":20,"obstacle":"back","note":"mi","twoTone":null},{"id":21,"obstacle":"backGate"},{},{"id":23,"obstacle":"vert"}],[{},{"id":25,"obstacle":"back"},{"id":26,"obstacle":"back","note":"sol","twoTone":null},{"id":27,"obstacle":"forward"},{},{"id":29,"obstacle":"back"},{"id":30,"obstacle":"back","note":"_do","twoTone":null},{"id":31,"obstacle":"forward"}]],"solution":[["_do"],[],[],["mi"],[],[],[],[],["fi"],[],[],[],["sol"],[],["fi"],[],["_do"],[],[],["mi"],[],[],[],[],["fi"],[],[],[],["sol"],[],["fi"],[],["_do"],[]],"viewportOffset":[0,0]}',
	47: '{"number":"47","author":"Chris","size":[11,5],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{},{},{},{},{},{},{},{}],[{},{"id":12,"obstacle":"forward"},{},{"id":14,"note":null,"twoTone":["mi","fi"],"obstacle":"hor"},{"id":15,"obstacle":"back"},{},{"id":17,"obstacle":"forward","note":null,"twoTone":["_do","sol"]},{"id":18,"obstacle":"hor"},{"id":19,"note":"sol","twoTone":null,"start":"left"},{"id":20,"obstacle":"back"},{}],[{},{"id":23,"obstacle":"vert"},{"id":24,"note":null,"twoTone":["mi","fi"]},{"id":25,"button":["5"]},{"id":26,"obstacle":"vert"},{"id":27,"note":"_do","twoTone":null},{"id":28,"obstacle":"vert"},{"id":29,"button":["3"]},{"id":30,"note":null,"twoTone":["mi","fi"]},{"id":31,"obstacle":"vert"},{}],[{},{"id":34,"obstacle":"back"},{"id":35,"note":"sol","twoTone":null,"start":"right"},{"id":36,"obstacle":"hor"},{"id":37,"obstacle":"forward","note":null,"twoTone":["_do","sol"]},{},{"id":39,"obstacle":"back"},{"id":40,"note":null,"twoTone":["mi","fi"],"obstacle":"hor"},{},{"id":42,"obstacle":"forward"},{}],[{},{},{},{},{},{},{},{},{},{},{}]],"solution":[["mi"],[],[],["_do"],[],[],["fi"],[],[],["sol"],[],[],["mi"],[],[],[],["mi"],[],[],["sol"],[],[],["fi"],[],[],["sol"],[],[]],"viewportOffset":[0,0]}',
	48: '{"number":"48","author":"Chris","size":[11,5],"wormholeStart":[5,1],"wormholeEnd":[5,3],"level":[[{},{},{"id":2,"obstacle":"forward"},{"id":3,"obstacle":"forward"},{"id":4,"obstacle":"back"},{"id":5,"obstacle":"forward","note":"do","twoTone":null},{"id":6,"obstacle":"hor"},{"id":7,"obstacle":"back","note":"mi","twoTone":null},{"id":8,"obstacle":"back"},{},{}],[{},{},{"id":13,"obstacle":"forward"},{"id":14,"obstacle":"backGate","note":"sol","twoTone":null},{"id":15,"obstacle":"back"},{"id":16,"wormhole":"wormholeStart","obstacle":"forward"},{"id":17,"button":["3","5"]},{"id":18,"obstacle":"backGate"},{"id":19,"obstacle":"back"},{},{}],[{},{"id":23,"start":"right"},{"id":24,"obstacle":"back","note":null,"twoTone":["_do","fa"]},{"id":25,"obstacle":"back"},{"id":26,"note":"fi","twoTone":null,"obstacle":"forward"},{"id":27,"obstacle":"forward"},{"id":28,"note":"fi","twoTone":null,"obstacle":"forward"},{"id":29,"obstacle":"back"},{"id":30,"obstacle":"back","note":null,"twoTone":["_do","fa"]},{"id":31,"start":"left"},{}],[{},{},{"id":35,"obstacle":"back"},{"id":36,"obstacle":"backGate"},{"id":37,"button":["5","3"]},{"id":38,"wormhole":"wormholeEnd","obstacle":"forward"},{"id":39,"obstacle":"back"},{"id":40,"obstacle":"backGate","note":"sol","twoTone":null},{"id":41,"obstacle":"forward"},{},{}],[{},{},{"id":46,"obstacle":"back"},{"id":47,"obstacle":"back","note":"mi","twoTone":null},{"id":48,"obstacle":"hor"},{"id":49,"obstacle":"forward","note":"do","twoTone":null},{"id":50,"obstacle":"back"},{"id":51,"obstacle":"forward"},{"id":52,"obstacle":"forward"},{},{}]],"solution":[["_do"],[],["sol"],[],["fa"],[],[],["mi"],[],[],["fi"],[],[],[],[],[],["fi"],[],[],["do"],[],[],["sol"],[],["_do"],[]],"viewportOffset":[0,0]}',
	49: '{"number":"49","author":"Chris","size":[11,5],"wormholeStart":[2,2],"wormholeEnd":[7,2],"level":[[{},{"id":1,"obstacle":"forward","note":"sol","twoTone":null},{"id":2,"obstacle":"back"},{},{},{},{},{"id":7,"obstacle":"forward"},{"id":8,"obstacle":"back","note":null,"twoTone":["mi","sol"]},{},{}],[{"id":11,"obstacle":"forward","note":"mi","twoTone":null},{},{},{"id":14,"obstacle":"back","note":"fi","twoTone":null},{},{},{"id":17,"obstacle":"forward","note":"fi","twoTone":null},{},{},{"id":20,"obstacle":"back","note":null,"twoTone":["do","sol"]},{}],[{"id":22,"obstacle":"back"},{"id":23,"start":"right"},{"id":24,"wormhole":"wormholeStart","obstacle":"back","note":"mi","twoTone":null},{},{"id":26,"obstacle":"back"},{"id":27,"obstacle":"forward"},{},{"id":29,"wormhole":"wormholeEnd","obstacle":"forward","note":"mi","twoTone":null},{"id":30,"start":"left"},{"id":31,"obstacle":"forward"},{}],[{},{"id":34,"obstacle":"back","note":"fi","twoTone":null},{},{},{"id":37,"obstacle":"forward","note":"do","twoTone":null},{"id":38,"obstacle":"back","note":null,"twoTone":["fa","do"]},{},{},{"id":41,"obstacle":"forward","note":"fi","twoTone":null},{},{}],[{},{},{"id":46,"obstacle":"back"},{"id":47,"obstacle":"forward","note":"fa","twoTone":null},{},{},{"id":50,"obstacle":"back","note":null,"twoTone":["sol","do"]},{"id":51,"obstacle":"forward"},{},{},{}]],"solution":[["mi"],[],[],["do"],[],[],["fi"],[],[],["sol"],[],[],["mi"],[],[],["do"],[],[],["fi"],[],[],["sol"],[],[],["mi"],[],[],["sol"],[],[],["fi"],[],[],["do"],[],[],["mi"],[],[],["sol"],[],[],["fi"],[],[],["do"],[],[]],"viewportOffset":[-100,0]}',
	50: '{"number":"50","author":"Chris","size":[11,5],"wormholeStart":[6,4],"wormholeEnd":[3,4],"level":[[{},{},{"id":2,"obstacle":"forward"},{"id":3,"note":null,"twoTone":["sol","fi"]},{"id":4,"obstacle":"hor"},{"id":5,"obstacle":"back"},{"id":6,"obstacle":"forward","note":null,"twoTone":["_do","fa"]},{},{"id":8,"obstacle":"vert","note":"mi","twoTone":null},{"id":9,"obstacle":"back"},{}],[{},{},{"id":13,"obstacle":"backGate"},{"id":14,"note":"_do","twoTone":null,"obstacle":"hor"},{"id":15,"button":["6","1","2"]},{"id":16,"note":"do","twoTone":null,"obstacle":"vert"},{},{"id":18,"obstacle":"back"},{},{"id":20,"note":null,"twoTone":["_do","fa"],"obstacle":"back"},{}],[{},{"id":23,"obstacle":"forward"},{"id":24,"note":"fa","twoTone":null,"button":["5","7","1"]},{"id":25,"obstacle":"backGate"},{"id":26,"twoTone":["sol","fi"],"note":null,"button":["5"]},{"id":27,"button":["8"]},{},{"id":29,"note":null,"twoTone":["sol","fi"]},{},{"id":31,"obstacle":"forward"},{}],[{},{"id":34,"note":"do","twoTone":null,"obstacle":"back"},{"id":35,"obstacle":"backGate"},{"id":36,"note":"mi","twoTone":null,"obstacle":"vert"},{"id":37,"start":"right"},{"id":38,"twoTone":["_do","fa"],"note":null},{"id":39,"button":["5","7"]},{"id":40,"obstacle":"vert"},{},{"id":42,"note":null,"twoTone":["_do","fa"],"obstacle":"back"},{}],[{},{"id":45,"obstacle":"back"},{},{"id":47,"wormhole":"wormholeEnd","obstacle":"forward"},{"id":48,"obstacle":"back"},{"id":49,"button":["5","1"]},{"id":50,"wormhole":"wormholeStart","obstacle":"back"},{"id":51,"note":"do","twoTone":null,"obstacle":"forward"},{"id":52,"note":"mi","twoTone":null,"obstacle":"vert"},{"id":53,"obstacle":"forward"},{}]],"solution":[["_do"],[],[],["sol"],[],[],["do"],[],[],["fi"],[],[],["fa"],[],["mi"],[],["_do"],[],[],["sol"],[],[],["do"],[],[],["fi"],[],[],["fa"],[],["mi"],[],["_do"],[],[],["sol"],[],[],["fi"],[],[],["fa"],[],["mi"],[],["_do"],[],[],["sol"],[],[],["fi"],[],[],["fa"],[],["mi"],[],["_do"],[],[],["sol"],[],[],["do"],[],["fa"],[],["mi"],[],["_do"],[]],"viewportOffset":[0,0]}',
	credits: '{"number":"-1","author":"Chris","size":[15,7],"wormholeStart":null,"wormholeEnd":null,"level":[[{"id":0,"obstacle":"forward"},{"id":1,"obstacle":"hor"},{"id":2,"button":["5","3"]},{"id":3,"obstacle":"back"},{"id":4,"button":["5","3"]},{"id":5,"obstacle":"back"},{"id":6,"button":["3","5"]},{"id":7,"obstacle":"back"},{"id":8,"obstacle":"back"},{"id":9,"obstacle":"forward"},{"id":10,"note":null,"twoTone":["sol","mi"],"obstacle":"back"},{"id":11,"obstacle":"forward","note":null,"twoTone":["_do","fi"]},{},{"id":13,"note":"_do","twoTone":null,"obstacle":"back"},{}],[{"id":15,"obstacle":"forward"},{"id":16,"button":["3"]},{"id":17,"obstacle":"back"},{"id":18,"obstacle":"forward","note":"do","twoTone":null},{"id":19,"obstacle":"back"},{},{"id":21,"obstacle":"vert"},{"id":22,"button":["5"]},{"id":23,"obstacle":"forward"},{},{},{"id":26,"obstacle":"vert"},{"id":27,"obstacle":"forward"},{},{"id":29,"obstacle":"back"}],[{},{},{"id":32,"start":"down"},{},{},{"id":35,"obstacle":"forward"},{"id":36,"note":"fi","twoTone":null},{"id":37,"note":"mi","twoTone":null},{"id":38,"obstacle":"back"},{"id":39,"obstacle":"backGate","note":"sol","twoTone":null},{},{"id":41,"note":"_do","twoTone":null},{"id":42,"button":["1","7"]},{"id":43,"note":"_do","twoTone":null},{"id":44,"obstacle":"forward"}],[{"id":45,"obstacle":"back"},{},{"id":47,"obstacle":"forward"},{},{},{"id":50,"note":"sol","twoTone":null},{},{},{},{},{"id":55,"note":"sol","twoTone":null},{},{"id":57,"obstacle":"forward"},{},{"id":59,"button":["1","7"]}],[{"id":60,"obstacle":"forward"},{},{"id":62,"obstacle":"back"},{"id":63,"obstacle":"forGate"},{"id":64,"note":"do","twoTone":null},{"id":65,"note":"fi","twoTone":null},{},{},{"id":68,"twoTone":["_do","do"],"note":null},{},{},{"id":71,"obstacle":"back","note":"_do","twoTone":null},{"id":72,"obstacle":"forGate"},{"id":73,"obstacle":"forward","note":"_do","twoTone":null},{"id":74,"obstacle":"vert"}],[{},{},{"id":77,"button":["1"]},{"id":78,"note":null,"twoTone":["do","_do"]},{},{"id":80,"obstacle":"back"},{"id":81,"note":"mi","twoTone":null},{"id":82,"start":"left"},{"id":83,"obstacle":"forward"},{"id":84,"note":"sol","twoTone":null,"obstacle":"back"},{"id":85,"obstacle":"forward"},{"id":86,"obstacle":"forward"},{},{"id":88,"button":["5"]},{"id":89,"obstacle":"back"}],[{"id":90,"obstacle":"back"},{"id":91,"start":"left"},{"id":92,"obstacle":"forward"},{"id":93,"obstacle":"back"},{"id":94,"obstacle":"forward"},{"id":95,"obstacle":"vert"},{"id":96,"start":"right"},{"id":97,"obstacle":"hor"},{"id":98,"button":["5","3"]},{"id":99,"obstacle":"back"},{"id":100,"button":["5","3"]},{"id":101,"obstacle":"back"},{"id":102,"obstacle":"vertGate"},{},{"id":104,"obstacle":"forward"}]],"solution":[],"viewportOffset":[0,0]}'
}

Sol.newLevels = [
	'{"number":"0","author":"Chris","size":[15,7],"level":[[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],[{},{},{},{},{},{},{},{},{},{},{},{},{},{},{}],[{},{},{},{"id":93,"start":"right"},{},{"id":95,"note":"_do"},{},{"id":97,"note":"mi"},{},{"id":99,"note":"sol"},{},{"id":101,"note":"do"},{},{},{}]],"solution":[["_do"],[],["mi"],[],["sol"],[],["do"],[],[],[]]}',
	/////////////////////////////////////////
	// _do, do and vertical gates introduced
	/////////////////////////////////////////
	'{"number":"1","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{},{},{},{},{}],[{},{"id":9,"note":"do","twoTone":null,"obstacle":"vertGate"},{"id":10,"start":"right"},{"id":11,"note":"_do","twoTone":null},{"id":12,"obstacle":"vertGate"},{"id":13},{"id":14,"note":"do","twoTone":null,"obstacle":"vertGate"},{"id":15}],[{},{},{},{},{},{},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],[],["do"],[],[],["_do"],[],["do"],[],[]],"viewportOffset":[0,-100]}',
	// rotating obstacles introduced
	'{"number":"2","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{},{},{},{},{}],[{},{"id":9,"note":"do","twoTone":null,"obstacle":"vert"},{"id":10,"start":"right"},{"id":11,"note":"_do","twoTone":null},{"id":12,"obstacle":"back"},{"id":13},{"id":14,"note":"do","twoTone":null,"obstacle":"hor"},{"id":15}],[{},{},{},{},{},{},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],[],["do"],[],[],["_do"],[],["do"],[],[]],"viewportOffset":[0,-100]}',
	/////////////////////////////////////////
	// sol introduced
	/////////////////////////////////////////
	'{"number":"3","author":"Chris","size":[8,4],"level":[[{},{},{},{},{},{},{},{}],[{},{},{},{"id":11,"note":"do","obstacle":"back"},{},{"id":13,"note":"_do","obstacle":"forward"},{},{}],[{},{},{},{"id":19,"start":"up"},{},{},{},{}],[{},{},{},{"id":27,"obstacle":"hor"},{"id":28,"note":"sol"},{"id":29,"obstacle":"forward"},{},{}]],"solution":[["do"],[],[],["sol"],[],[],["_do"],[],["do"],[],[],[]],"viewportOffset":[100,100]}',
	// diagonal gates introduced
	'{"number":"4","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{"id":2,"obstacle":"back"},{"id":3,"obstacle":"backGate","note":"do","twoTone":null},{},{},{},{}],[{},{"id":9,"start":"right"},{"id":10,"obstacle":"backGate","note":"_do","twoTone":null},{"id":11,"obstacle":"backGate"},{"id":12,"obstacle":"backGate"},{},{},{}],[{},{},{},{"id":19,"obstacle":"backGate"},{"id":20,"note":"sol","twoTone":null,"obstacle":"back"},{"id":21},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],[],["sol"],[],[],["do"],[],["_do"],[],[],[]],"viewportOffset":[-100,-100]}',
	'{"number":"5","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{"id":3,"obstacle":"back","note":"sol"},{"id":4,"obstacle":"back"},{},{},{}],[{},{},{},{},{},{},{},{}],[{},{},{"id":18,"start":"right"},{"id":19,"obstacle":"backGate"},{"id":20,"obstacle":"forward","note":"_do"},{},{},{}],[{},{},{},{"id":27,"obstacle":"back","note":"do"},{"id":28,"obstacle":"back"},{},{},{}]],"solution":[["do"],[],[],["sol"],[],[],["_do"],[],["do"],[],[],[]],"viewportOffset":[0,0]}',
	// wormholes introduced
	'{"number":"6","author":"Chris","size":[8,4],"wormholeEnd":[7,1],"level":[[{},{},{},{},{},{},{},{}],[{"id":8,"wormhole":"wormholeStart"},{"id":9,"note":"do","twoTone":null,"obstacle":"vertGate"},{"id":10,"obstacle":"hor"},{"id":11,"note":"do","twoTone":null,"obstacle":"hor"},{"id":12,"start":"right"},{"id":13,"obstacle":"vertGate","note":"_do","twoTone":null},{"id":14,"obstacle":"hor"},{"id":15,"wormhole":"wormholeEnd"}],[{},{},{},{},{},{},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],[],["do"],[],[],["_do"],[],["do"],[],[],[]],"viewportOffset":[0,-100],"wormholeStart":[0,1]}',
	'{"number":"7","author":"Chris","size":[8,4],"wormholeStart":[3,1],"wormholeEnd":[4,2],"level":[[{},{},{},{},{},{},{},{}],[{},{},{"id":10,"obstacle":"vert","note":"do","twoTone":null},{"id":11,"wormhole":"wormholeStart"},{"id":12,"start":"right"},{"id":13,"obstacle":"back","note":"_do","twoTone":null},{},{}],[{},{"id":17},{"id":18,"obstacle":"back"},{"id":19,"note":"sol","twoTone":null,"obstacle":"forward"},{"id":20,"wormhole":"wormholeEnd"},{"id":21,"obstacle":"forward"},{},{}],[{},{},{},{"id":27},{},{},{},{}]],"solution":[["_do"],[],[],["sol"],[],["do"],[],[],["_do"],[],[],[]],"viewportOffset":[0,0]}',
	'{"number":"8","author":"Chris","size":[8,4],"wormholeStart":[3,1],"wormholeEnd":[4,2],"level":[[{},{},{},{},{},{},{},{}],[{},{},{"id":10,"obstacle":"back"},{"id":11,"wormhole":"wormholeStart"},{"id":12,"note":"_do","twoTone":null,"obstacle":"back"},{"id":13,"obstacle":"back"},{},{}],[{},{},{"id":18,"note":"sol","twoTone":null,"obstacle":"forward"},{"id":19,"obstacle":"forGate"},{"id":20,"wormhole":"wormholeEnd"},{"id":21,"obstacle":"forward","note":"do","twoTone":null},{},{}],[{},{},{},{"id":27,"start":"up"},{},{},{},{}]],"solution":[["_do"],[],[],["sol"],[],[],["do"],[],["_do"],[],[],[]],"viewportOffset":[0,100]}',
	'{"number":"9","author":"Chris","size":[8,4],"level":[[{},{},{"id":2},{"id":3,"obstacle":"forward","note":"sol","twoTone":null},{"id":4},{"id":5,"obstacle":"back"},{},{}],[{},{},{"id":10},{"id":11,"wormhole":"wormholeStart"},{"id":12,"obstacle":"hor"},{"id":13,"obstacle":"forGate","note":"_do","twoTone":null},{},{}],[{},{},{"id":18},{"id":19,"obstacle":"forGate","note":"_do","twoTone":null},{"id":20,"start":"up"},{"id":21,"wormhole":"wormholeEnd"},{},{}],[{},{},{"id":26},{"id":27,"obstacle":"back"},{"id":28,"note":"do","twoTone":null},{"id":29,"obstacle":"forward"},{},{}]],"solution":[["_do"],[],["_do"],[],["_do"],[],[],["sol"],[],[],["do"],[],[],[]],"viewportOffset":[100,0],"wormholeStart":[3,1],"wormholeEnd":[5,2]}',
	'{"number":"10","author":"Chris","size":[8,4],"level":[[{},{},{"id":2,"obstacle":"forward","note":"_do","twoTone":null},{"id":3,"obstacle":"forGate"},{"id":4,"obstacle":"back","note":"do","twoTone":null},{},{},{}],[{},{},{"id":10},{"id":11,"note":"_do","twoTone":null,"obstacle":"horGate"},{"id":12},{},{},{}],[{},{},{"id":18,"wormhole":"wormholeStart"},{"id":19,"start":"up"},{"id":20,"wormhole":"wormholeEnd"},{},{},{}],[{},{},{"id":26,"obstacle":"back","note":"sol","twoTone":null},{"id":27,"obstacle":"forward"},{"id":28,"obstacle":"forward","note":"do","twoTone":null},{},{},{}]],"solution":[["_do"],[],["do"],[],[],["sol"],[],[],["do"],[],["_do"],[],[],[]],"viewportOffset":[-100,0],"wormholeStart":[2,2],"wormholeEnd":[4,2]}',
	// interaction between wormholes and notes introduced
	'{"number":"11","author":"Chris","size":[8,4],"wormholeStart":[4,2],"wormholeEnd":[2,0],"level":[[{},{},{"id":2,"wormhole":"wormholeEnd","note":"_do","twoTone":null},{},{"id":4,"obstacle":"back","note":"do","twoTone":null},{},{},{}],[{},{},{"id":10,"obstacle":"horGate"},{},{"id":12,"obstacle":"horGate"},{},{},{}],[{},{},{"id":18,"obstacle":"back"},{"id":19,"start":"left"},{"id":20,"wormhole":"wormholeStart","note":"sol","twoTone":null},{},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],["sol"],[],[],[],["sol"],[],["do"],[],[],[],[]],"viewportOffset":[-100,-100]}',
	'{"number":"12","author":"Chris","size":[8,4],"wormholeStart":[4,1],"wormholeEnd":[2,2],"level":[[{},{},{"id":2,"obstacle":"forward"},{"id":3,"obstacle":"forGate","note":"_do","twoTone":null},{"id":4,"start":"left"},{},{},{}],[{},{},{"id":10,"obstacle":"forward"},{"id":11,"obstacle":"forGate"},{"id":12,"wormhole":"wormholeStart","note":"sol","twoTone":null},{},{},{}],[{},{},{"id":18,"wormhole":"wormholeEnd","note":"do","twoTone":null},{"id":19,"obstacle":"backGate"},{"id":20,"obstacle":"forward"},{},{},{}],[{},{},{},{"id":27},{},{},{},{}]],"solution":[["_do"],[],[],["do"],[],[],[],["sol"],[],[],["sol"],[],[],["_do"],[],[],[]],"viewportOffset":[-100,-100]}',
	// interaction between wormholes and obstacles introduced
	'{"number":"13","author":"Chris","size":[8,4],"wormholeEnd":[4,1],"level":[[{},{},{},{},{},{},{},{}],[{},{"id":9},{"id":10,"obstacle":"forward"},{"id":11,"obstacle":"hor","note":"do","twoTone":null},{"id":12,"wormhole":"wormholeEnd"},{"id":13,"obstacle":"hor"},{"id":14,"start":"left"},{}],[{"id":16},{"id":17},{"id":18,"note":"_do","twoTone":null,"obstacle":"back"},{"id":19,"wormhole":"wormholeStart","obstacle":"vertGate"},{"id":20,"obstacle":"hor"},{"id":21,"obstacle":"vert","note":"_do","twoTone":null},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],[],["do"],[],["_do"],[],["do"],[],[]],"viewportOffset":[100,0],"wormholeStart":[3,2]}',
	'{"number":"14","author":"Chris","size":[8,4],"wormholeStart":[2,1],"wormholeEnd":[5,1],"level":[[{},{},{},{},{},{},{},{}],[{"id":8},{"id":9,"obstacle":"vertGate","note":"do","twoTone":null},{"id":10,"wormhole":"wormholeStart","obstacle":"forward"},{"id":11,"obstacle":"vertGate","note":"do","twoTone":null},{"id":12,"obstacle":"vertGate","note":"_do","twoTone":null},{"id":13,"wormhole":"wormholeEnd","obstacle":"forward"},{"id":14,"start":"right"},{"id":15,"note":"_do","twoTone":null,"obstacle":"vertGate"}],[{},{},{},{},{},{},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],[],["do"],[],["_do"],[],["do"],[],[],[]],"viewportOffset":[100,-100]}',
	'{"number":"15","author":"Chris","size":[8,4],"wormholeStart":[2,1],"wormholeEnd":[5,3],"level":[[{},{},{},{},{},{},{},{}],[{},{"id":9},{"id":10,"wormhole":"wormholeStart"},{"id":11,"note":"sol","twoTone":null,"obstacle":"forGate"},{"id":12,"obstacle":"hor"},{},{},{}],[{},{"id":17},{"id":18,"obstacle":"hor","note":"do","twoTone":null},{"id":19,"obstacle":"forward"},{"id":20,"obstacle":"backGate"},{"id":21,"note":"_do","twoTone":null,"obstacle":"hor"},{"id":22},{}],[{},{},{"id":26},{"id":27,"start":"up"},{"id":28,"note":"do","twoTone":null,"obstacle":"hor"},{"id":29,"wormhole":"wormholeEnd"},{},{}]],"solution":[["do"],[],["_do"],[],[],["sol"],[],[],["_do"],[],["do"],[],[],[]],"viewportOffset":[0,100]}',
	'{"number":"16","author":"Chris","size":[8,4],"wormholeStart":[3,1],"wormholeEnd":[4,1],"level":[[{},{},{},{"id":3,"obstacle":"forward"},{"id":4,"note":"_do","twoTone":null,"obstacle":"back"},{},{},{}],[{},{},{"id":10,"start":"right"},{"id":11,"wormhole":"wormholeStart","obstacle":"forward"},{"id":12,"wormhole":"wormholeEnd","obstacle":"forward"},{"id":13,"note":"do","twoTone":null,"obstacle":"vert"},{},{}],[{},{},{},{"id":19,"obstacle":"back"},{"id":20,"note":"sol","twoTone":null,"obstacle":"forward"},{},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["do"],[],[],["_do"],[],[],["sol"],[],[],["_do"],[],[],[]],"viewportOffset":[0,-100]}'
]

/*New potential levels:
three note loop with extra note: {"number":"99","author":"Chris","size":[8,4],"level":[[{},{},{"id":2,"obstacle":"forward","note":"_do","twoTone":null},{"id":3,"obstacle":"forGate"},{"id":4,"obstacle":"back","note":"do","twoTone":null},{},{},{}],[{},{},{"id":10},{"id":11,"note":"_do","twoTone":null,"obstacle":"horGate"},{"id":12},{},{},{}],[{},{},{"id":18,"wormhole":"wormholeStart"},{"id":19,"start":"up"},{"id":20,"wormhole":"wormholeEnd"},{},{},{}],[{},{},{"id":26,"obstacle":"back","note":"sol","twoTone":null},{"id":27,"obstacle":"back"},{"id":28,"obstacle":"forward","note":"sol","twoTone":null},{},{},{}]],"solution":[["_do"],[],[],["sol"],[],[],["do"],[],["_do"],[],[],["sol"],[],[],["do"],[],["_do"],[],[],[]],"viewportOffset":[-100,0],"wormholeStart":[2,2],"wormholeEnd":[4,2]}

*/


/*Potential Levels:
{"number":"2","author":"Chris","size":[8,4],"level":[[{},{},{},{},{},{},{},{}],[{},{},{},{"id":11,"obstacle":"vert"},{"id":12,"note":"do","obstacle":"back"},{"id":13,"note":"do","obstacle":"vert"},{},{}],[{},{},{"id":18,"start":"right"},{"id":19,"note":"_do","obstacle":"hor"},{"id":20,"obstacle":"forward"},{"id":21,"note":"_do","obstacle":"back"},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],["do"],[],["_do"],["do"],["do"]]}
{"number":"5","author":"Chris","size":[8,4],"level":[[{},{},{},{},{},{},{},{}],[{},{},{"id":10,"note":"sol","obstacle":"forward"},{"id":11,"obstacle":"vert"},{"id":12,"note":"sol"},{},{"id":14,"obstacle":"back"},{}],[{},{},{"id":18,"obstacle":"forward"},{"id":19,"note":"_do"},{"id":20,"obstacle":"back"},{},{"id":22,"note":"_do","obstacle":"hor"},{}],[{},{},{},{"id":27,"start":"up"},{},{},{},{}]],"solution":[["_do"],[],["sol"],[],[],["_do"],[],[],["_do"],[],["sol"],[],["_do"]],"viewportOffset":[100,0]}
{"number":"6","author":"Chris","size":[8,4],"level":[[{},{},{},{},{},{},{},{}],[{},{},{},{"id":11,"obstacle":"vert"},{"id":12,"note":"do","obstacle":"back"},{"id":13,"note":"do","obstacle":"vert"},{},{}],[{},{},{"id":18,"start":"right"},{"id":19,"note":"_do","obstacle":"hor"},{"id":20,"obstacle":"forward"},{"id":21,"note":"_do","obstacle":"back"},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],["_do"],["do"],["do"],[],["_do"],[],["do"],["do"],["_do"],[],["_do"]],"viewportOffset":[0,0]}
{"number":"4","author":"Chris","size":[8,4],"wormholeStart":[6,2],"wormholeEnd":[3,1],"level":[[{},{},{"id":2,"obstacle":"forward"},{"id":3,"obstacle":"vert"},{},{},{},{}],[{},{},{"id":10,"note":"_do"},{"id":11,"wormhole":"wormholeEnd"},{"id":12,"note":"sol"},{"id":13,"obstacle":"hor"},{"id":14,"obstacle":"back"},{}],[{},{},{"id":18,"obstacle":"forward"},{"id":19,"note":"do","obstacle":"back"},{"id":20,"start":"right"},{"id":21,"note":"_do"},{"id":22,"wormhole":"wormholeStart"},{}],[{},{},{},{},{},{"id":29,"obstacle":"back"},{"id":30,"obstacle":"hor","note":"do"},{}]],"solution":[["_do"],[],["sol"],[],["_do"],[],["do"],[],[],[],["_do"],[],["do"],[]],"viewportOffset":[100,0]}
{"number":"4","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{},{},{},{},{}],[{},{},{},{"id":11,"note":"sol","obstacle":"vert"},{"id":12,"obstacle":"vert"},{"id":13,"obstacle":"back"},{},{}],[{},{"id":17,"start":"right"},{"id":18,"note":"_do"},{"id":19,"obstacle":"backGate"},{"id":20,"obstacle":"backGate"},{"id":21,"obstacle":"backGate","note":"_do"},{},{}],[{},{},{},{"id":27,"obstacle":"vert"},{"id":28,"note":"do","obstacle":"vert"},{"id":29,"obstacle":"forward"},{},{}]],"solution":[["_do"],[],[],[],["sol"],[],[],["do"],[],["_do"],[],[],["_do"]],"viewportOffset":[0,100]}
{"number":"5","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{},{},{},{},{}],[{},{},{"id":10,"obstacle":"forward"},{"id":11,"obstacle":"vertGate"},{"id":12,"note":"sol"},{"id":13,"obstacle":"hor"},{},{}],[{},{},{"id":18,"obstacle":"vert","note":"do"},{"id":19,"start":"right"},{"id":20,"note":"_do","obstacle":"vertGate"},{"id":21,"obstacle":"forward"},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[["_do"],[],["do"],[],[],["sol"],[],["sol"],[],[],["do"],[],["_do"]],"viewportOffset":[0,0]}
{"number":"5","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{"id":3,"start":"down"},{},{},{},{}],[{},{},{"id":10,"obstacle":"vert"},{"id":11,"note":"_do"},{"id":12,"obstacle":"back"},{},{},{}],[{},{},{"id":18,"note":"do","obstacle":"forward"},{"id":19,"obstacle":"backGate"},{"id":20,"obstacle":"forward"},{},{},{}],[{},{},{"id":26,"obstacle":"back"},{"id":27,"obstacle":"hor"},{"id":28,"note":"sol","obstacle":"forward"},{},{},{}]],"solution":[["_do"],[],[],["sol"],[],[],["do"],[],[],["sol"],[],[],["do"]],"viewportOffset":[-100,0]}

//symmetrical 
{"number":"45","author":"Chris","size":[8,4],"wormholeStart":[0,0],"wormholeEnd":[7,3],"level":[[{"id":0,"wormhole":"wormholeStart","note":"do"},{"id":1,"obstacle":"hor"},{},{},{},{},{},{}],[{"id":8,"obstacle":"vert"},{"id":9,"obstacle":"backGate"},{},{"id":11,"note":"_do"},{"id":12,"start":"left"},{},{"id":14,"obstacle":"vert","note":"sol"},{}],[{},{"id":17,"obstacle":"vert","note":"sol"},{},{"id":19,"start":"right"},{"id":20,"note":"_do"},{},{"id":22,"obstacle":"backGate"},{"id":23,"obstacle":"vert"}],[{},{},{},{},{},{},{"id":30,"obstacle":"hor"},{"id":31,"wormhole":"wormholeEnd","note":"do"}]],"solution":[["_do"],[],[],[],["do"],[],[],[],["_do"],[],[],["sol"],[],[],["do"],[],[],["sol"],[],[],["_do"]],"viewportOffset":[0,0]}
//original level 20, replaced by Futurama
{"number":"20","author":"Chris","size":[8,4],"wormholeStart":[5,2],"wormholeEnd":[3,1],"level":[[{},{},{},{"id":3,"obstacle":"forward"},{"id":4,"obstacle":"forward","note":"do"},{"id":5,"obstacle":"back"},{},{}],[{},{},{},{"id":11,"wormhole":"wormholeEnd"},{"id":12,"obstacle":"back"},{"id":13,"obstacle":"back","note":"sol"},{},{}],[{},{},{},{"id":19,"start":"right","note":"_do"},{"id":20,"obstacle":"forGate","note":"fa"},{"id":21,"wormhole":"wormholeStart"},{},{}],[{},{},{},{"id":27,"obstacle":"back"},{"id":28,"obstacle":"backGate"},{"id":29,"obstacle":"forward","note":"_do"},{},{}]],"solution":[["fa"],[],["sol"],[],["_do"],[],[],["_do"],[],[],["do"],[],[],["_do"],[],[],["_do"],[],["sol"],[],["fa"]],"viewportOffset":[100,0]}

{"number":"0","author":"Chris","size":[8,4],"wormholeStart":[4,2],"wormholeEnd":[2,1],"level":[[{},{},{},{"id":3,"obstacle":"forward"},{"id":4,"note":"fa","twoTone":null,"obstacle":"backGate"},{},{},{}],[{},{"id":9,"obstacle":"forward","twoTone":null,"note":"fa"},{"id":10,"wormhole":"wormholeEnd"},{"id":11,"obstacle":"back","twoTone":["do","sol"],"note":null},{"id":12,"obstacle":"forward"},{"id":13,"obstacle":"back"},{},{}],[{},{"id":17,"obstacle":"back"},{"id":18,"start":"right"},{"id":19,"note":null,"twoTone":["_do","sol"],"obstacle":"forGate"},{"id":20,"wormhole":"wormholeStart"},{"id":21,"obstacle":"forward","note":"sol","twoTone":null},{},{}],[{},{},{"id":26,"note":"fa","twoTone":null,"obstacle":"backGate"},{"id":27,"obstacle":"forward"},{},{},{},{}]],"solution":[["do"],[],[],["fa"],[],["sol"],[],[],["fa"]],"viewportOffset":[0,0]}

Simple Imperial March:
{"number":"0","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{"id":2,"obstacle":"forward"},{"id":3,"note":"sol","twoTone":null,"obstacle":"back"},{"id":4,"obstacle":"backGate"},{"id":5,"obstacle":"back"},{"id":6,"obstacle":"forward"},{"id":7,"obstacle":"back"}],[{},{},{"id":10,"start":"right"},{"id":11,"note":"mi","twoTone":null,"obstacle":"backGate"},{"id":12,"obstacle":"back"},{"id":13,"note":"_do","twoTone":null},{"id":14,"obstacle":"forward"},{"id":15,"note":"mi","twoTone":null}],[{},{},{},{"id":19,"obstacle":"back"},{"id":20,"obstacle":"backGate"},{"id":21,"obstacle":"forward"},{},{}],[{},{},{},{},{"id":28,"obstacle":"back"},{"id":29,"note":"mi","twoTone":null},{},{"id":31,"obstacle":"forward"}]],"solution":[[]],"viewportOffset":[0,0]}

Mysterious sounding:
{"number":"0","author":"Chris","size":[8,4],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{"id":1,"obstacle":"forward"},{"id":2,"note":"fi","twoTone":null},{"id":3,"obstacle":"forward"},{"id":4,"note":"fi","twoTone":null},{"id":5,"obstacle":"back"},{},{}],[{},{"id":9,"note":"sol","twoTone":null,"obstacle":"back"},{"id":10,"obstacle":"forGate"},{"id":11,"obstacle":"back"},{"id":12,"obstacle":"backGate"},{"id":13,"note":"sol","twoTone":null,"obstacle":"forward"},{},{}],[{},{"id":17,"obstacle":"back"},{"id":18,"start":"up"},{"id":19,"twoTone":["_do","mi"],"note":null,"obstacle":"forward"},{"id":20,"start":"up"},{"id":21,"obstacle":"forward"},{},{}],[{},{},{},{},{},{},{},{}]],"solution":[[]],"viewportOffset":[0,0]}

pyramid:
{"number":"0","author":"Chris","size":[8,4],"wormholeStart":[1,1],"wormholeEnd":[5,1],"level":[[{},{},{},{"id":3,"note":"do","twoTone":null},{},{},{},{}],[{},{"id":9,"wormhole":"wormholeStart","obstacle":"hor"},{"id":10,"note":"mi","twoTone":null,"obstacle":"back"},{"id":11,"obstacle":"backGate"},{"id":12,"note":"fa","twoTone":null,"obstacle":"forward"},{"id":13,"wormhole":"wormholeEnd","obstacle":"hor"},{},{}],[{},{"id":17,"note":"sol","twoTone":null,"obstacle":"hor"},{"id":18,"start":"right"},{"id":19,"note":"_do","twoTone":null,"obstacle":"forGate"},{},{"id":21,"note":"fi","twoTone":null},{},{}],[{},{"id":25,"obstacle":"back"},{},{"id":27,"obstacle":"forward"},{},{"id":29,"obstacle":"forward"},{},{}]],"solution":[["fi"]],"viewportOffset":[-100,0]}

half-steps:
{"number":"47","author":"Chris","size":[11,5],"wormholeStart":null,"wormholeEnd":null,"level":[[{},{},{},{},{},{},{},{},{},{},{}],[{},{},{"id":13,"obstacle":"forward","note":"mi","twoTone":null},{"id":14,"button":["6"]},{"id":15,"obstacle":"back","note":"fa","twoTone":null},{"id":16,"obstacle":"forward"},{"id":17,"obstacle":"forward","note":"fi","twoTone":null},{"id":18,"button":["8"]},{"id":19,"obstacle":"back","note":"sol","twoTone":null},{},{}],[{},{},{"id":24,"obstacle":"back"},{"id":25,"start":"right"},{},{"id":27,"note":"_do","twoTone":null,"obstacle":"hor"},{},{"id":29,"start":"left"},{"id":30,"obstacle":"back"},{},{}],[{},{},{"id":35,"obstacle":"back","note":"sol","twoTone":null},{"id":36,"button":["0"]},{"id":37,"obstacle":"forward","note":"fi","twoTone":null},{"id":38,"obstacle":"forward"},{"id":39,"obstacle":"back","note":"fa","twoTone":null},{"id":40,"button":["2"]},{"id":41,"obstacle":"forward","note":"mi","twoTone":null},{},{}],[{},{},{},{},{},{},{},{},{},{},{}]],"solution":[[],["_do"],[],["_do"],[],[],[],["mi"],[],["fa"],[],["fi"],[],["sol"],[],[],[],["_do"],[],["_do"],[],[],[],["sol"],[],["fi"],[],["fa"],[],["mi"],[],[],[],["_do"],[],["_do"],[],[],[]],"viewportOffset":[0,0]}

symmetrical wormhole obstacles:
{"number":"0","author":"Chris","size":[11,5],"wormholeStart":[3,1],"wormholeEnd":[7,3],"level":[[{},{},{"id":2,"obstacle":"forward"},{"id":3,"obstacle":"back"},{"id":4,"note":"mi","twoTone":null,"obstacle":"forward"},{"id":5,"obstacle":"back"},{},{},{},{},{}],[{},{"id":12,"obstacle":"forward"},{"id":13,"note":"_do","twoTone":null},{"id":14,"wormhole":"wormholeStart","obstacle":"vert"},{"id":15,"obstacle":"back"},{},{"id":17,"obstacle":"back"},{"id":18,"obstacle":"forward"},{"id":19,"note":"sol","twoTone":null,"obstacle":"back"},{},{}],[{},{"id":23,"obstacle":"back"},{"id":24,"start":"right"},{"id":25,"button":["1"]},{"id":26,"obstacle":"forward"},{"id":27,"note":"do","twoTone":null},{"id":28,"obstacle":"forward"},{"id":29,"button":["7"]},{"id":30,"start":"left"},{"id":31,"obstacle":"back"},{}],[{},{},{"id":35,"note":"sol","twoTone":null,"obstacle":"back"},{"id":36,"obstacle":"forward"},{"id":37,"obstacle":"back"},{},{"id":39,"obstacle":"back"},{"id":40,"wormhole":"wormholeEnd","obstacle":"vert"},{"id":41,"note":"_do","twoTone":null},{"id":42,"obstacle":"forward"},{}],[{},{},{},{},{},{"id":49,"obstacle":"back"},{"id":50,"note":"mi","twoTone":null,"obstacle":"forward"},{"id":51,"obstacle":"back"},{"id":52,"obstacle":"forward"},{},{}]],"solution":[["fi"]],"viewportOffset":[0,0]}

Final Level Sketches:
{"number":"0","author":"Chris","size":[11,5],"wormholeStart":[8,1],"wormholeEnd":[1,2],"level":[[{"id":0,"obstacle":"forward"},{"id":1,"obstacle":"back"},{"id":2,"obstacle":"forward"},{},{"id":4,"note":"fi","twoTone":null},{},{"id":6,"obstacle":"forGate"},{"id":7,"note":"mi","twoTone":null,"obstacle":"back"},{},{},{}],[{"id":11,"obstacle":"forGate"},{"id":12,"obstacle":"backGate"},{"id":13,"note":"sol","twoTone":null},{},{"id":15,"obstacle":"vert"},{"id":16,"obstacle":"forward"},{"id":17,"button":["1"]},{"id":18,"button":["5"]},{"id":19,"wormhole":"wormholeStart","obstacle":"forGate"},{},{}],[{},{"id":23,"wormhole":"wormholeEnd"},{"id":24,"start":"down"},{"id":25,"start":"left"},{"id":26,"note":"fi","twoTone":null,"button":["7"]},{"id":27,"obstacle":"forward"},{},{"id":29,"note":"sol","twoTone":null},{},{},{}],[{},{},{"id":35,"note":"_do","twoTone":null,"obstacle":"back"},{},{"id":37,"obstacle":"forGate"},{"id":38,"note":"fi","twoTone":null,"button":["7"]},{},{"id":40,"obstacle":"forward"},{},{},{}],[{"id":44,"obstacle":"back"},{"id":45,"obstacle":"hor"},{"id":46,"note":"do","twoTone":null},{},{},{"id":49,"obstacle":"back"},{},{},{"id":52,"note":"sol","twoTone":null,"obstacle":"forward"},{},{}]],"solution":[["_do"],[],["sol"],[],["fa"],[],[],["mi"],[],[],["fi"],[],[],[],[],[],["fi"],[],[],["do"],[],[],["sol"],[],["_do"],[]],"viewportOffset":[0,0]}
{"number":"50","author":"Chris","size":[11,5],"wormholeStart":[6,4],"wormholeEnd":[3,4],"level":[[{},{},{"id":2,"obstacle":"forward"},{"id":3,"note":"fi","twoTone":null},{"id":4,"obstacle":"hor"},{"id":5,"obstacle":"back"},{"id":6,"obstacle":"forward","note":"do","twoTone":null},{},{"id":8,"obstacle":"vert","note":"mi","twoTone":null},{"id":9,"obstacle":"back"},{}],[{},{},{"id":13,"obstacle":"backGate"},{"id":14,"note":"_do","twoTone":null,"obstacle":"back"},{"id":15,"button":["6","1","2"]},{"id":16,"note":"fi","twoTone":null,"obstacle":"back"},{},{"id":18,"obstacle":"back"},{},{"id":20,"note":null,"twoTone":["_do","sol"],"obstacle":"back"},{}],[{},{"id":23,"obstacle":"forward"},{"id":24,"note":"sol","twoTone":null,"button":["5","7","1"]},{"id":25,"obstacle":"backGate"},{"id":26,"note":"fi","twoTone":null,"button":["5"]},{"id":27,"button":["8"]},{},{"id":29,"note":"fi","twoTone":null},{},{"id":31,"obstacle":"forward"},{}],[{},{"id":34,"note":"do","twoTone":null,"obstacle":"back"},{"id":35,"obstacle":"backGate"},{"id":36,"note":"mi","twoTone":null,"obstacle":"forward"},{"id":37,"start":"right"},{"id":38,"twoTone":["_do","sol"],"note":null},{"id":39,"button":["5","7"]},{"id":40,"obstacle":"vert"},{},{"id":42,"note":null,"twoTone":["sol","_do"],"obstacle":"back"},{}],[{},{"id":45,"obstacle":"back"},{},{"id":47,"wormhole":"wormholeEnd","obstacle":"forward"},{"id":48,"obstacle":"back"},{"id":49,"button":["5","1"]},{"id":50,"wormhole":"wormholeStart","obstacle":"back"},{"id":51,"note":"do","twoTone":null},{"id":52,"note":"mi","twoTone":null,"obstacle":"vert"},{"id":53,"obstacle":"forward"},{}]],"solution":[["_do"],[],[],["fi"],[],[],["fi"],[],[],["fi"],[],[],["sol"],[],["mi"],[],["_do"],[],[],["fi"],[],[],["fi"],[],[],["fi"],[],[],["sol","_do"],[],["mi","do"],[],["_do","fa"],[],["sol"],[],["_do","do"],[]],"viewportOffset":[0,0]}
{"number":"50","author":"Chris","size":[11,5],"wormholeStart":null,"wormholeEnd":null,"level":[[{"id":0,"note":"do","twoTone":null,"obstacle":"forward"},{"id":1,"obstacle":"back"},{"id":2,"obstacle":"forward"},{"id":3,"note":"fi","twoTone":null},{"id":4,"obstacle":"hor"},{"id":5,"obstacle":"back"},{},{"id":7,"obstacle":"forward"},{"id":8,"note":"_do","twoTone":null,"obstacle":"forward"},{"id":9,"obstacle":"forward"},{"id":10,"note":"mi","twoTone":null,"obstacle":"back"}],[{"id":11,"obstacle":"forward"},{"id":12,"obstacle":"back"},{"id":13,"obstacle":"backGate"},{"id":14,"note":"_do","twoTone":null,"obstacle":"back"},{"id":15,"start":"down"},{"id":16,"note":"fi","twoTone":null,"obstacle":"vert"},{},{"id":18,"obstacle":"back"},{"id":19,"obstacle":"back"},{"id":20,"note":"sol","twoTone":null,"obstacle":"back"},{}],[{"id":22,"obstacle":"vert"},{"id":23,"obstacle":"back"},{"id":24,"note":"sol","twoTone":null,"button":["5","1"]},{"id":25,"obstacle":"backGate"},{"id":26,"obstacle":"backGate","twoTone":["_do","fi"],"note":null},{"id":27,"obstacle":"backGate"},{"id":28,"button":["3"]},{"id":29,"note":"fi","twoTone":null},{"id":30,"obstacle":"hor"},{},{"id":32,"note":"_do","twoTone":null,"obstacle":"back"}],[{"id":33,"obstacle":"vert"},{"id":34,"note":"do","twoTone":null},{"id":35,"obstacle":"back"},{"id":36,"note":"mi","twoTone":null,"obstacle":"back"},{"id":37,"start":"right"},{"id":38,"twoTone":["_do","sol"],"note":null},{},{"id":40,"obstacle":"forward"},{"id":41,"obstacle":"hor"},{"id":42,"note":"fa","twoTone":null,"obstacle":"vert"},{}],[{"id":44,"obstacle":"back"},{"id":45,"obstacle":"hor"},{},{"id":47,"obstacle":"hor"},{"id":48,"obstacle":"forGate"},{},{},{"id":51,"obstacle":"back"},{"id":52,"note":"_do","twoTone":null,"obstacle":"back"},{"id":53,"obstacle":"back"},{"id":54,"note":"do","twoTone":null,"obstacle":"forward"}]],"solution":[["_do"],[],[],["fi"],[],[],["fi"],[],[],["fi"],[],[],["sol"],[],["mi"],[],["_do"],[],[],["fi"],[],[],["fi"],[],[],["fi"],[],[],["sol","_do"],[],["mi","do"],[],["_do","fa"],[],["sol"],[],["_do","do"],[]],"viewportOffset":[0,0]}
*/